apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo-cluster
  region: us-east-1
  version: "1.31"

privateCluster:
  enabled: true

vpc:
  subnets:
    private:
      us-east-1a:
        id: <eks-private-subnet-1-id>
      us-east-1b:
        id: <eks-private-subnet-2-id>

managedNodeGroups:
  - name: general
    instanceType: t4g.medium
    desiredCapacity: 2
    privateNetworking: true
    volumeSize: 20
