apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: coffeeshop-shopping-spc
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "<secrets-manager-arn-shopping>"
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
      - objectName: "<secrets-manager-arn-token>"
        jmesPath:
          - path: jwtAccessSecret
            objectAlias: jwtAccessSecret
          - path: jwtRefreshSecret
            objectAlias: jwtRefreshSecret
  secretObjects:
    - secretName: coffeeshop-shopping-secret
      type: Opaque
      data:
        - objectName: username
          key: DB_USERNAME
        - objectName: password
          key: DB_PASSWORD
    - secretName: coffeeshop-token-secret
      type: Opaque
      data:
        - objectName: jwtAccessSecret
          key: JWT_ACCESS_SECRET
        - objectName: jwtRefreshSecret
          key: JWT_REFRESH_SECRET
