apiVersion: v1
kind: ConfigMap
metadata:
  name: coffeeshop-shopping-config
data:
  DB_HOST: host.minikube.internal
  DB_PORT: "5432"
  DB_DBNAME: <database_shopping>
  API_CUSTOMER_URL: http://coffeeshop-customer-svc.default.svc.cluster.local:4000/api/customer
---
apiVersion: v1
kind: Secret
metadata:
  name: coffeeshop-customer-secret
type: Opaque
stringData:
  DB_USERNAME: <username>
  DB_PASSWORD: <password>
