apiVersion: v1
kind: ConfigMap
metadata:
  name: coffeeshop-shopping-config
data:
  API_CUSTOMER_URL: http://eks-demo-coffeeshop-customer-svc.default.svc.cluster.local:4000
---
apiVersion: v1
kind: Secret
metadata:
  name: coffeeshop-customer-secret
type: Opaque
stringData:
  DB_USERNAME: <username>
  DB_PASSWORD: <password>
  DB_HOST: host.minikube.internal
  DB_PORT: "5432"
  DB_DBNAME: <database_customer>
