apiVersion: v1
kind: Secret
metadata:
  name: coffeeshop-customer-secret
type: Opaque
stringData:
  DB_USERNAME: <username>
  DB_PASSWORD: <password>
  DB_HOST: host.minikube.internal
  DB_PORT: "5432"
  DB_DBNAME: <database_customer>
