apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop-shopping-deploy
  labels:
    app: coffeeshop-shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffeeshop-shopping
  template:
    metadata:
      labels:
        app: coffeeshop-shopping
    spec:
      containers:
        - name: eks-demo-coffeeshop-shopping
          image: mortredn/eks-demo-coffeeshop-shopping:latest
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
          ports:
            - containerPort: 4000
          env:
            - name: API_CUSTOMER_URL
              valueFrom:
                configMapKeyRef:
                  name: coffeeshop-shopping-config
                  key: API_CUSTOMER_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: coffeeshop-shopping-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coffeeshop-shopping-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: coffeeshop-shopping-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: coffeeshop-shopping-secret
                  key: DB_PORT
            - name: DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: coffeeshop-shopping-secret
                  key: DB_DBNAME
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: coffeeshop-token-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: coffeeshop-token-secret
                  key: JWT_REFRESH_SECRET
